# Generated by Django 4.1 on 2022-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='FilialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='catalog.filial', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_prices', to='catalog.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_characteristics', to='catalog.characteristic', verbose_name='Parent')),
                ('product', models.ManyToManyField(related_name='characteristics', to='catalog.product', verbose_name='Products')),
            ],
        ),
    ]
